Revert "battery: sec_battery: export {CURRENT/VOLTAGE}_MAX to sysfs"
../drivers/battery/common/sec_battery.c:6935:7: error: duplicate case value 'POWER_SUPPLY_PROP_VOLTAGE_MAX'
 6935 |         case POWER_SUPPLY_PROP_VOLTAGE_MAX:
      |              ^
../drivers/battery/common/sec_battery.c:6912:7: note: previous case defined here
 6912 |         case POWER_SUPPLY_PROP_VOLTAGE_MAX:
      |              ^
../drivers/battery/common/sec_battery.c:6939:7: error: duplicate case value 'POWER_SUPPLY_PROP_CURRENT_MAX'
 6939 |         case POWER_SUPPLY_PROP_CURRENT_MAX:
      |              ^
../drivers/battery/common/sec_battery.c:6916:7: note: previous case defined here
 6916 |         case POWER_SUPPLY_PROP_CURRENT_MAX:
      |              ^
2 errors generated.
make[3]: *** [../scripts/Makefile.build:273: drivers/battery/common/sec_battery.o] Error 1
make[3]: *** Waiting for unfinished jobs....

This reverts commit 31a102d09bd1c844a2a9476b21f4622d6f7cb1aa.

Signed-off-by: Ksawlii <ksawery.blaszczak@proton.me>