Revert "lz4: fix kernel decompression speed"
../lib/lz4/lz4_decompress.c:545:4: error: implicit declaration of function 'LZ4_memmove' [-Werror,-Wimplicit-function-declaration]
  545 |                         LZ4_memmove(op, ip, length);
      |                         ^
../lib/lz4/lz4_decompress.c:545:4: note: did you mean '__memmove'?
../arch/arm64/include/asm/string.h:40:14: note: '__memmove' declared here
   40 | extern void *__memmove(void *, const void *, __kernel_size_t);
      |              ^
1 error generated.

This reverts commit b9c94ba82354924e2757a64a24e99805fe8a49ac.

Signed-off-by: Ksawlii <ksawery.blaszczak@proton.me>